### ISSUE TITLE
go nodes command does not work in some cases

### ISSUE THREAD

**Issue by BrennusJ** [AndyGrant/Ethereal#174] opened 2021-03-13 14:45 UTC
Hello,

I compile it with under Linux 64 using Intel(R) Core(TM) i3-9100F CPU (AVX) 
make -j8 relaese using this modify line in makefile :
$(CC) $(RFLAGS) $(SRC) $(LIBS) $(AVX2FLAGS) $(PEXTFLAGS) -o ../dist/$(EXE)$(VER)-x64-pext-avx2
i use it under Scid
here down the log file 

_Scid  : uci
Engine: id name Ethereal 12.89 (PEXT)
Engine: id author Andrew Grant, Alayan & Laldon
Engine: option name Hash type spin default 16 min 2 max 131072
Engine: option name Threads type spin default 1 min 1 max 2048
Engine: option name MultiPV type spin default 1 min 1 max 256
Engine: option name ContemptDrawPenalty type spin default 0 min -300 max 300
Engine: option name ContemptComplexity type spin default 0 min -100 max 100
Engine: option name MoveOverhead type spin default 100 min 0 max 10000
Engine: option name SyzygyPath type string default <empty>
Engine: option name SyzygyProbeDepth type spin default 0 min 0 max 127
Engine: option name Ponder type check default false
Engine: option name AnalysisMode type check default false
Engine: option name UCI_Chess960 type check default false
Engine: uciok
Scid  : isready
Engine: readyok
Scid  : setoption name Hash value 512
Scid  : isready
Engine: info string set Hash to 512MB
Engine: readyok
Scid  : setoption name Threads value 4
Scid  : isready
Engine: info string set Threads to 4
Engine: readyok
Scid  : setoption name MultiPV value 3
Scid  : isready
Engine: info string set MultiPV to 3
Engine: readyok
Scid  : setoption name Ponder value false
Scid  : isready
Engine: readyok
Scid  : setoption name ContemptDrawPenalty value 0
Scid  : isready
Engine: info string set ContemptDrawPenalty to 0
Engine: readyok
Scid  : setoption name ContemptComplexity value 0
Scid  : isready
Engine: info string set ContemptComplexity to 0
Engine: readyok
Scid  : setoption name MoveOverhead value 100
Scid  : isready
Engine: info string set MoveOverhead to 100
Engine: readyok
Scid  : setoption name SyzygyPath value <empty>
Scid  : isready
Engine: info string set SyzygyPath to <empty>
Engine: readyok
Scid  : setoption name SyzygyProbeDepth value 0
Scid  : isready
Engine: info string set SyzygyProbeDepth to 0
Engine: readyok
Scid  : setoption name AnalysisMode value false
Scid  : isready
Engine: info string set AnalysisMode to false

Scid  : isready
Engine: readyok
Scid  : position startpos moves e2e4 c7c5 g1f3 d7d6 d2d4 c5d4 f3d4 g8f6 b1c3 g7g6 c1e3 f8g7 f2f3 e8g8 d1d2 b8c6 f1c4 c8d7 e1c1 d8a5 c4b3 f8c8 h2h4 c6e5 c1b1 e5c4 b3c4 c8c4 d4b3 a5c7 e3d4 d7e6 h4h5 a7a5 h5g6 h7g6 a2a4 b7b5 c3b5 c7b8 b5c3 c4b4 h1h4 e6b3 c2b3 b4b3 c3b5 b3b4 d2c2 b8b7 d4c3 a8c8 b1a2 b4c4 b2b3 c4c3 c2c3
**Scid  : go nodes 9999999
Engine: info depth 1 seldepth 1 multipv 1 score cp 515 time 0 nodes 3 nps 3000 tbhits 0 hashfull 0 pv c8c3 
Engine: info depth 1 seldepth 1 multipv 2 score cp -387 time 0 nodes 23 nps 23000 tbhits 0 hashfull 0 pv e7e6 
Engine: info depth 1 seldepth 1 multipv 3 score cp -473 time 0 nodes 35 nps 35000 tbhits 0 hashfull 0 pv e7e5 
Engine: bestmove c8c3**
Scid  : stop
Scid  : isready
Engine: readyok_

why it is not computing until reach the expected number of nodes (99999999) ?
it is stopping only after 35 nodes

Regards

**Comment by AndyGrant** [comment] 2021-03-14 01:28
Currently, if you take a peek at the code you'll see there is no support for ``go nodes <x>`` as well as ``go mate <x>``. So not a bug, just a missing feature. You can leave this issue open and I might do it at some point, but there are some questions to ask:

First one being what do you do if you have 32 threads running? Do I constantly check the sum total of all threads and when the sum exceeds ``<x>`` I kill the search? Or do I wait until the main thread has reached ``<x>`` nodes? Or until the main thread has reached ``<x> / 32`` nodes?

**Comment by BrennusJ** [comment] 2021-03-14 12:34
Ok Andy, in fact 3 other engines where running in same time in my i3-9100F (maximum of 8 threads), i will test to check again without any GUI (scid). All engines where running using a settings of 4 threads
Why i want to use nodes : I want to discover a function that link the ELO value and number of nodes computed
About expected new features : something that make eval function simple : for exemple only material to exclude any deep chess knowledge.

The goal of this : i'm 57 y/o and when during the 80' i play against decicated computer with a very limited hardware and software many computer match with my level (around 1500 ELO) and i get a really deep pleasure to play against it and win.
The function to limit ELO that use random in many other engine to make lower the level is a really bas idea for a goog playing feeling because the engine is playing very good and suddenly it give you his Queen making you win and make your feeling (it let me win). Old dedicated computer give material only to try to escape mate.

in my opinion : 1500 nodes give 1500 ELO and each time you double the number of nodes you add 150-200 ELO points

**Comment by BrennusJ** [comment] 2021-03-14 13:30
Here a screen capture after a new test
[https://photos.app.goo.gl/hG5qQrkxzB3PqyMK8](url)
![Capture d’écran_2021-03-14_14-26-40](https://user-images.githubusercontent.com/3634605/111070370-c13d8d80-84d1-11eb-8f08-dcbf7df5f600.png)

**Comment by BrennusJ** [comment] 2021-03-14 17:59
Ok i think iunderstand reading the code in uci.c that "nodes" seems not to be implemented

**Comment by BrennusJ** [comment] 2021-03-14 18:06
ok now i finaly understand your question Andy but i need to think about it : the first thing that came in my mind is : "Wait the last thead to return and then stop even if it override the node limit" the nodes limit is only a minimum. I think for you it is simpler to implement like this. Do you think if i set 10000 it could be 20000 if we wait the last thread to finish ? because the nodes limit is only to lower the ELO why not set the thread to 1 in case of use of go nodes command ?
Sorry about my misunderstanding : how do the other engine ?

**Comment by lucasart** [comment] 2021-03-26 00:29
> Do I constantly check the sum total of all threads and when the sum exceeds `<x>` I kill the search? Or do I wait until the main thread has reached `<x>` nodes? Or until the main thread has reached `<x> / 32` nodes?

What I do in Demolito is the first one. I have a timer thread, separate from the search threads. It just loops; each iteration of the loop sleeps for 5ms, then checks various conditions (including sum of nodes > limit); when it detect a termination condition, sets an abort_search flag for search threads to observe.

Second solution is clearly a hack, but, does the average user deserve better ? As long as the nodes displayed looks not too far off, they will be happy. In practice, it's impossible to comply with fixed nodes in SMP search. You inevitably have overshoot.

**Comment by AndyGrant** [comment] 2021-06-02 05:28
Implemented and resolved via https://github.com/AndyGrant/Ethereal/commit/2d3215f9952a5b4bf255bc653458d458bc4e2a98

**Closed as completed by AndyGrant** 2021-06-02 05:28 UTC
